export { default as Dashboard } from './Dashboard/Dashboard.jsx';
export { default as Login } from './Login/Login.jsx';
export { default as Signup } from './Signup/signup.jsx';
export { default as Team } from './Team/Team.jsx';
export { default as Contacts } from './Contacts/Contacts.jsx';
export { default as Expense } from './Expense/Expense.jsx';
export { default as Calendar } from './Calendar/Calendar.jsx';
export { default as FAQ } from './FAQ/FAQ.jsx';
export { default as Geography } from './Geography/Geography.jsx';